# AWS region to run in
region: "us-west-2"
# autoscaling groups to discover by tag
tags:
  - key: "kubernetes.io/cluster/my-cluster"
    value: "owned"
  - key: "eks:nodegroup-name"
    value: "my-spot-nodegroup"
# autoscaling group activity causes
causes:
  - pattern: ".*Spot Instance interruption notice.*"
    reason: "interrupt"
  - pattern: ".*EC2 instance rebalance recommendation.*"
    reason: "rebalance"
  - pattern: ".*user request.*"
    reason: "user_request"
